### PR TITLE
Add indexes to columns used in plugin joins

### PR DESCRIPTION
**Pull request by rmulhol**
- Will probably want to update these depending on what's commonly used
  in join/where statements.

### CODE REVIEW

**Comment by i-norden** [comment]
Hrrm looks like we may have a new flaky test (same one as on staging yesterday)

`
time="2019-06-19T20:05:36Z" level=error msg="RetrieveAndUpdateBlocks: error getting block: not found"
• Failure [3.899 seconds]
Reading from the Geth blockchain
/home/travis/gopath/src/github.com/vulcanize/vulcanizedb/integration_test/geth_blockchain_test.go:36
  reads two blocks [It]
  /home/travis/gopath/src/github.com/vulcanize/vulcanizedb/integration_test/geth_blockchain_test.go:50
  Expected error:
      <*errors.errorString | 0xc00003e680>: {s: "not found"}
      not found
  not to have occurred
  /home/travis/gopath/src/github.com/vulcanize/vulcanizedb/integration_test/geth_blockchain_test.go:57
`
Not sure why it's acting up all of a sudden :(

**Comment by m0ar** [comment]
@i-norden Are the tests using Infura? They've been known not to return events etc on queries, could that have anything to do with it? Should we try using Alchemy and see if it persists?

**Comment by i-norden** [comment]
@m0ar yeah we are still using infura for the integration tests (Travis's private env variable). I'm not familiar with Alchemy but will look into them, also if we have arch0 up and running we should be able to use that? I don't know what the endpoint is for that though, or if/how we would need to configure authentication for it.

**Comment by m0ar** [comment]
@i-norden No idea about `arch0`. @rmulhol ?

**Comment by m0ar** [comment]
I'd assume so. @rmulhol ?

**Pull request merged**
